version: '3.0'

services: 

  db: 
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: task_manager
    ports: 
      - 5432:5432
    volumes: 
      - app-volume:/var/lib/postgresql/data

  db-test:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: task_manager_test
    ports: 
      - 8080:5432

volumes:
  app-volume: